### ISSUE TITLE
Open up event/request pipeline customization to more use cases

### ISSUE THREAD

**Issue by JonasSamuelsson** [JonasSamuelsson/Handyman#99]
Some customizations can't be combined with the current implementation (`request handler experiments` and `when any request handler` for instance).

To enable the possibility to combine different customizations a customization should be implemented as a combination of a `filter/handler selector` and `filter/handler` rather than a `execution strategy`.  
The order in which the selectors are executed must be customizable.
Selectors with the same order value should be executed in the order they are declared.

- [x] #101 [add event pipeline builder attribute ordering](https://github.com/JonasSamuelsson/Handyman/issues/101)
- [x] #102 [add request pipeline builder attribute ordering](https://github.com/JonasSamuelsson/Handyman/issues/102)
- [x] #104 [reimplement request handler experiments](https://github.com/JonasSamuelsson/Handyman/issues/104)
- [x] #103 [reimplement when any request handler](https://github.com/JonasSamuelsson/Handyman/issues/103)
